version: '3.8'

services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - ./env/backend.env
    volumes:
      - ../backend:/app
      - static_volume:/app/static
    depends_on:
      - db
    networks:
      - app_network

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: frontend
    env_file:
      - ./env/frontend.env
    volumes:
      - ../frontend:/app
    networks:
      - app_network

  db:
    image: postgres:13
    container_name: db
    env_file:
      - ./env/postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/static
    depends_on:
      - backend
      - frontend
    networks:
      - app_network

volumes:
  postgres_data:
  static_volume:

networks:
  app_network:
    driver: bridge
