# Generated by Django 5.1.5 on 2025-01-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faq", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="faq",
            name="number_of_faqs",
            field=models.PositiveIntegerField(default=3),
        ),
    ]
