# Generated by Django 5.1.5 on 2025-01-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faq", "0002_faq_number_of_faqs"),
    ]

    operations = [
        migrations.AddField(
            model_name="faq",
            name="tone",
            field=models.CharField(
                choices=[
                    ("formal", "Formal"),
                    ("netural", "Neutral"),
                    ("casual", "Casual"),
                ],
                default="neutral",
            ),
        ),
    ]
