# Generated by Django 5.1.5 on 2025-01-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faq", "0003_faq_tone"),
    ]

    operations = [
        migrations.AddField(
            model_name="faq",
            name="category",
            field=models.CharField(default="General", max_length=255),
        ),
    ]
